version: '3.8'
name: architecture
services:
  redis_architecture:
    image: redis:latest
    container_name: redis_architecture
    hostname: redis
    volumes:
      - /var/lib/redis
    ports:
      - '6378:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - HOST=${REDIS_HOST}
    env_file:
      - .env
  postgres_architecture:
    image: postgres:12-alpine
    container_name: postgres12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=kientruc
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # server:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   container_name: server_prod
  #   ports:
  #     - '8081:8080'

  #   depends_on:
  #     - rabbitmq_prod
  #     - redis_prod
  #   networks:
  #     - backend_network

volumes:
  redis:
    driver: local
  postgres_data:
